language: c++

matrix:
    include:
        - os: linux
          dist: xenial
          env:
              - TARGET=x86_64-unknown-linux-gnu
              - EVAL_CXX="CC=gcc-8 && CXX=g++-8"
          addons:
              apt:
                  update: true
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - g++-8
                      - libsdl2-dev
                      - libsdl2-image-dev
          compiler: g++-8
        - os: linux
          dist: xenial
          env:
              - TARGET=x86_64-unknown-linux-gnu
              - EVAL_CXX="CC=clang-7 && CXX=clang++-7"
          addons:
              apt:
                  update: true
                  sources:
                      - llvm-toolchain-xenial-7
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - clang-7
                      - libstdc++-7-dev
                      - libsdl2-dev
                      - libsdl2-image-dev
          compiler: clang++-7
        - os: osx
          osx_image: xcode10.2
          env:
              - EVAL_CXX="CC=gcc && CXX=g++"
          compiler: g++
        - os: osx
          osx_image: xcode10.2
          compiler: clang++

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_image; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libsdl2-dev libsdl2-image-dev; fi

script:
    - mkdir build
    - cd build
    - eval "${EVAL_CXX}"
    - cmake ..
    - make -j$(nproc)
    - cd tests
    - ctest -Q -O ctest_log.txt
    - cat ctest_log.txt

notification:
    email:
        on_success: never
        on_failure: change

